i18next.init({
    lng: (navigator.language || navigator.userLanguage || navigator.systemLanguage || navigator.browserLanguage),
    supportedLngs: ['am-ET', 'en-US', 'fr-FR', 'de-DE', 'it-IT', 'es-ES'],
    resources: {
        "en-US": {
            translation: {
                CANCEL: 'Cancel',
                OPTIONS: 'Options',
                NAME: 'Name',
                TOURS: 'Tours',
                GROUPS: 'Groups',
                COMPANY_REGISTRATION: "Company Registration",
                GROUP_SEASON: "Group Season",
                CUSTOM_TOUR: 'Custom Tour',
                NEW_GROUP: 'New Group',
                SIGN_IN: 'Sign in',
                LOGIN: 'Login',
                USER_NAME: 'User name',
                PASSWORD: 'Password',
                COPYRIGHT: 'Copyright',
                FLIGHTS: 'Flights',
                HOTELS: 'Hotels',
                BUNDLE_DEALS: 'Bundle Deals',
                CARS: 'Cars',
                CRUISES: 'Cruises',
                THINGS_TODO: 'Things to Do',
                VACATION_RENTALS: 'Vacation Rentals',
                SEARCH: 'Search',
                ROUND_TRIP: 'Round Trip', 
                ONE_WAY: 'One Way', 
                MULTIPLE_DESTINATIONS: 'Multiple Destinations', 
                FLIGHT_HOTEL: 'Flight + Hotel', 
                FLIGHT_HOTEL_CAR: 'Flight + Hotel + Car', 
                FLIGHT_CAR: 'Flight + Car', 
                HOTEL_CAR: 'Hotel + Car',
                REGISTER: 'Register',
                REGISTER_COMPANY: 'Register Company',
                HELP: 'Help',
                MORE: 'More',
                PAGE_NOT_FOUND: "The Functionality you requested is not supported at this time",
                WE_COULDNT_FIND_THE_PAGE: "Sorry, we couldn't find the page you were looking for.",
                LET_US_KNOW_IF_U_FIND_IT: "Please let us know if find you it",
                FESTIVALS_AND_EVENTS: "Upcoming Festivals and Events",
                EMAIL: 'Email',
                TOUR_TYPE: 'Tour Type',
                TRAVELLERS: 'Travellers',
                TRIP_DATE: 'Trip Date',
                ALL_INCLUSIVE: 'All Inclusive',
                TRIP_DURATION: 'Trip Duration',
                DESCRIPTION: 'Description',
                GROUP_NAME: 'Group Name',
                CREATE_GROUP: 'Create Group',
                SUBMIT: 'Submit',
                DAYS: 'Days',
                JAN: 'Jan',
                SEP: 'Sep',
                APR: 'Apr',
                AUG: 'Aug',
                SELECT_LANGUGAGE: 'Select Language',
                SELECT_VISITING_COUNTRY: 'Select Visiting Country',
                GENNA: 'Camel Derby and Festival - Kenya',
                GENNA_PAR1: 'The Maralal Camel Derby is an annual event, held midyear just outside of Maralal town. This is Kenya’s best known and most prestigious camel race, attracting both local and international competitors. The event is a major draw for spectators as well as racers, and the competition is fierce.',
                GENNA_PAR2: 'The Maralal Camel derby is more than just a race. It is an entertaining festival of fun and local competition that brings this small desert town to life. If you are visiting Kenya during the race period, don’t miss Maralal.',
                TIMKET: 'The Great Migration',
                TIMKET_PAR1: 'During April-May in central Serengeti. The herds start moving north towards the centre of the park at this time of year. With all the newborn wildebeest, this is a time when the herd size is especially high. Central, southern Serengeti is the place to be as the herds amble northwards, getting ready for the big push towards Lobo and the far north.',
                TIMKET_PAR2: 'June often sees the herd split up into two large groups. Some start to move directly north, whereas the largest ‘mega’ herd sweeps round to the western corridor. This is a major migration month as the herds push north. It is also the time of year when the herds cross Grumeti River.',
                TIMKET_PAR3: 'This is a major migration month as the herds are in the middle of their major push north. The first herds start crossing the crocodile-infested Mara River – it is a fabulous time to be in this remote part of the park.',
                FASIKA: 'Fasika (Orthodox Easter)',
                FASIKA_PAR1: 'Easter is one of the most colorfully celebrated festivals in the Ethiopian Orthodox church and is a more important festival than Christmas, as death has greater meaning than birth in Orthodox Christianity. Like the other festivals, Easter is colorfully celebrated at Axum and Lalibela.',
                FASIKA_PAR2: 'On Easter Eve people go to church and celebrate with candles which are lit and form an important part of the Easter Mass Service which begins at 6 pm and ends at about 2 am. Afterwards everyone returns home to break their fast.',
                ENKUTATASH: 'Enkutatash (Ethiopian New Year)',
                ENKUTATASH_PAR1: 'Ethiopia still retains the Julian calendar in which the year is divided into 12 months of 30 days each and a 13th month of 5 days with 6 days in a leap year. The New Year is celebrated on 11th September and the day itself is called Enkutatash, which means “gift of jewels.”  It is a most spectacular event.',
                ENKUTATASH_PAR2: 'This festival celebrates both the New Year and the Feast of John the Baptist. This special spring event has been celebrated since early times and as the rains come to an end. Children dressed in new clothes dance through the villages distributing garlands and tiny paintings. In the evening each house lights a bonfire and there is much singing and dancing.',
                MESKEL: 'Meskel (Finding of the True Cross)',
                MESKEL_PAR1: 'The actually word Meskel means "cross" and the feast commemorates the discovery of the cross upon which Jesus was crucified by the Empress Helena, the mother of Constantine the Great.',
                MESKEL_PAR2: 'This day is celebrated with plenty of food and drink and believers go to the spot of the Demera and, using ashes from the fire, mark their foreheads with the sign of the cross. The most ideal place to see the Meskel Festival is in the capital Addis Ababa at the famous Meskel Square but all along the historic route (Bahir Dar, Gonder, Axum, and Lalibela) and in other major towns, Meskel is colorfully celebrated.',
                MESKEL_PAR3: 'Meskal has been celebrated in the country for over 1600 years and is a very popular festival in Ethiopia and gives everyone the opportunity to sing, dance and dress in colourful robes.',
                ADDIS_ABABA: 'Addis Ababa',
                ADDIS_ABABA_DESC: 'Since its establishment in 1886, Addis Ababa (Amharic: አዲስ አበባ) has always seemed a magical portal, ...',
                LALIBELA: 'Lalibela - Ethiopia',
                LALIBELA_DESC: 'Lalibela is history and mystery frozen in stone, its soul alive with the rites and awe of Christianity at its most ancient and unbending. ...',
                GONDAR: 'Gondar',
                GONDAR_DESC: 'It’s not what Gonder is, but what Gonder was that’s so enthralling. The city lies in a bowl of hills where tall trees shelter ...',
                AXUM: 'Axum',
                AXUM_DESC: 'Does the very same Ark of the Covenant that holds Moses’ 10 Commandments reside in a small Aksum chapel?...',
                DIREDAWA: 'Diredawa',
                DIREDAWA_DESC: 'The fourth-most populous city in Ethiopia, Dire Dawa usually elicits strong reactions. We think We think its colourful storefront, ...',
                HARAR: 'Harar',
                HARAR_DESC: 'The town of Harar dates from before the thirteenth century. Its strategic location between the coastal lowlands ...',
                SEMIEN_MOUNTAINS: 'Semien Mountains',
                SEMIEN_MOUNTAINS_DESC: 'No matter how you look at them, the Simien Mountains are awesome. This massive plateau, riven with gullies and pinnacles, ...',
                DALLOL: 'Dallol (Volcano)',
                DALLOL_DESC: 'The term Dallol was coined by the Afar people and means dissolution or disintegration describing a landscape made up of ...',
                THE_LOWER_OMO_VALLEY: 'The Lower Omo Valley',
                THE_LOWER_OMO_VALLEY_DESC: 'The villages of the Lower Omo Valley are home to some of Africa’s most fascinating ethnic groups and a trip here represents ...',
                ROCK_HEWN_CHURCHES_OF_TIGRAY: 'Rock-hewn Churches of Tigray',
                ROCK_HEWN_CHURCHES_OF_TIGRAY_DESC: 'The landscapes of northern Tigray are almost fairytale-like. The luminous light bathes scattered sharp peaks that rise ...',
                BALE_MOUNTAINS_NATIONAL_PARK: 'Bale Mountains National Park',
                BALE_MOUNTAINS_NATIONAL_PARK_DESC: 'More than any other park in Ethiopia, this soon-to-be World Heritage site is known for its wildlife, ...',
                DANAKIL_DEPRESSION: 'Danakil Depression',
                DANAKIL_DEPRESSION_DESC: 'Bubbling volcanoes light up the night sky, sulphurous mounds of yellow contort into otherworldly shapes, ...',
                BACK: 'Back',
                INFORMATION: 'Information',
                WARNING: 'Warning',
                FAILED: 'Failed',
                SUCCESS: 'Success',
                FIRST_NAME: 'First Name',
                LAST_NAME: 'Last Name',
                CONFIRM_PASSWORD: 'Confirm Password',
                SEX: 'Sex',
                BIRTHDAY: 'Birthday',
                PHONE_NUMBER: 'Phone Number',
                NDARYPHONE_NUMBER: 'Phone Number 2',
                LOCATION: 'Location',
                CLOSE: 'Close',
                SELECT: 'Select',
                DATE: 'Date',
                TRIP_STARTS_AT: 'Trip starts on',
                PEOPLE_IN_GROUP: 'people in this group.',
                FOUND_NOTHING: 'Found nothing',
                MATCHES: 'Matches',
                ADD_ME: 'Add Me',
                CONNECTION_ERROR: 'Sorry, we could not connect to our server. Please, check if your device is connected to internet.',
                OTHER: 'Other',
                COUNTRY: 'Country',
                INCLUDING_ACCOMMODATION_AND_MEAL: 'Including accommodation and meal',
                MALE: 'Male',
                FEMALE: 'Female',
                CONFIRM_PASSWORD_WARNING: 'The two passwords you entered don\'t match.',
                PICKING_UP: 'Picking Up',
                DROPPING_OFF: 'Dropping Off',
                PICKUP_DATE: 'Pick up Date',
                DROPOFF_DATE: 'Drop off Date',
                TRAVEL_AGENT_NAME: 'Travel Agent',
                FAX: 'Fax',
                AIRPORT_PICKUP: 'Airport Pickup',
                CAR_RENTAL_ONLY: 'Car Rental Company Only',
                CITY: 'City',
                SUB_CITY: 'Sub-City',
                COUNTY: 'Woreda',
                KEBELE: 'Kebele',
                BUILDING_NAME: 'Building',
                PACKAGE_REGISTRATION: 'Tour Package Registration',
                TOUR_MAX_SIZE: 'Group Max Size',
                TOUR_MIN_SIZE: 'Group Min Size',
                TOUR_START_DATE: 'Tour Start Date',
                TOUR_END_DATE: 'Tour End Date',
                TOUR_DURATION: 'Trip Length',
                TOUR_START_PLACE: 'Starting Address',
                TOUR_END_PLACE: 'Ending Address',
                TOUR_START_TIME: 'Starting Time',
                TOUR_ROUTE: 'Tour Route',
                TOUR_DESCRIPTION: 'Tour Itinerary',
                ALL_YEAR_ROUND_TRIP: 'All Year Round Trip',
                FIXED_DATE_TRIP: 'Fixed Date Trip',
                TOUR_PACKAGES: 'Tour Packages',
                CAR_REGISTRY: 'Car Rental',
                SEASON: 'Season(s)',
                BASIC_ONLY: 'Basic Only',
                MAKE: 'Make',
                MODEL: 'Model',
                PASSENGER_SIZE: 'Passenger Size',
                DOOR_COUNT: 'Doors',
                RETURN_ADDRESS_THE_SAME: 'Is Return Address the Same?',
                CARS_COUNT: 'No. of Cars',
                HOUSE_NUMBER: 'House Number',
                CAR_REGISTRATION: 'Car Registration',
                WITH_DRIVER: 'Only With Company Driver?',
                DAILY_PRICE: 'Daily Price',
                YES: 'Yes',
                TRIP_START_DATE: 'Trip Start Date',
                TRIP_END_DATE: 'Trip End Date',
                ETHIOPIA: 'Ethiopia',
                KENYA: 'Kenya',
                TANZANIA: 'Tanzania',
                UGANDA: 'Uganda',
                CONGO: 'Congo', 
                MOROCCO: 'Morocco', 
                SOUTH_AFRICA: 'South Africa',
                MALI: 'Mali', 
                ZAMBIA: 'Zambia', 
                ZIMBABWE: 'Zimbabwe', 
                EGYPT: 'Egypt', 
                TUNISIA: 'Tunisia', 
                GHANA: 'Ghana',
                SAME_AS_PICKUP: 'Same as Pick-up',
                TOURS_DESCRIPTION_1: 'Search, Choose and Book your Africa adventure!',
                TOURS_DESCRIPTION_2:'We have the widest choices of well designed tours for individuals and groups throughout Africa!',
                TOURS_DESCRIPTION_3: 'Travelling in groups of two or more and sharing memories is more fun and easier to make your dream vacation a reality with a limited budget. Please check the Groups tab to see if your interest and time frame matches with other like minded travelers.',
                AUTOMATIC_TRANSMISSION: 'Automatic Transmission?',
                MY_CARS: 'My Cars',
                MY_TOURS: 'My Tours',
                CAR_ID: 'Car Id',
                
                PRIVACY_POLICY:	'Privacy Policy',
                TERMSOF_SERVICE: 'Terms Of Service',
                ABOUT_TOURANB:	'About Touranb',
                COMPANY_URL: 'Website URL',
                TOUR_ID: 'Tour Id',
                PICKUP_TIME: ' P U',
                NOBOOKED_TOURS: 'You haven\'t booked any tour',
                BOOKED_TOURS: 'booked tours',
                BOOKED_CARS: 'booked tours',
                NOBOOKED_CARS: 'You haven\'t booked any car',
                NO_GROUPS: 'You haven\'t created a group',
                NOT: 'You haven\'t created a group',
                NO_GROUPS: 'You are not in any group',
                IN_GROUPS: 'Groups you are a member in',
                TRIPTO: 'Your trip to ',
                STARING_ON: 'Starting on',
                FOR: 'for',
                TOTAL_PRICE: 'Total Price',
                USD: 'USD',
                PRICE_NOT_GURANTED: 'Prices not guranteed until booked',
                CANCEL_TOUR: 'Free cancellation within 24 hours of booking!',
                BILLING_ADDRESS1: 'Billing Address 1',
                BILLING_ADDRESS2: 'Billing Address 2',
                CONFIRMATION_EMAIL_LABEL1: 'Where should we send your confirmation?',
                CONFIRMATION_EMAIL_LABEL2: 'Please enter the email address where you would like to receive your confirmation.',
                STARTING_ON: 'Starting on',
                TRAVELER: 'Traveler:',
                ADULT: 'Adult',
                ADULTS: 'Adults',
                TAX: 'Taxes',
                BOOKING_FEE: 'Booking Fee',
                TRIP_TOTAL: 'Trip Total: ',
                RATE_IN_USD: 'Rates are quoted in US dollars',
                COMPLETE_BOOKING: 'Complete Booking',
                CONTINUE_BOOKING: 'Continue Booking',
                TRIP_SUMMARY: 'Trip Summary',
                REVIEW_TRIP: 'Review your trip',
                WHO_TRAVELING: 'Who is traveling?',
                PASSPORT_NAME: 'Traveler name must match government-issued ID exactly',
                MIDDLE_NAME: 'Middle Name',
                PASSPORT_COUNTRY: 'Passport Country',
            	DATE_OF_BIRTH: 'Date of birth',
        		CARD_HOLDER_NAME: 'Cardholder Name',
        		CREDIT_CARD_NUMBER: 'Debit/Credit card number',   				
    			EXPERIATION_DATE: 'Expiration Date',
				SECURITY_CODE: 'Security Code',
				HOW_TO_PAY: ' How would like to pay? ', 
				ZIP_CODE: 'Zip Code',	
				EMAIL_ADDRESS: 'Email Address',
				STATE: 'State',
				OPERATOR_PHONE: 'Operator Phone : ',
				PAYMENT_SECURED: 'We use secure transmission and encrypted storage to protect your personal information.',
				TRIP_TO: 'Trip to ',
				ANY_TIME_OF: 'Any time of the year',
				ANY_NUMBER_OF: 'Any number of',
				TOUR_RESULTS: 'Tour Results',
				GROUP_RESULTS: 'Group Results',
				NO_ITINERARY: 'No itinerary to show',
				MONTH: 'Month',
				YEAR: 'Year',
				BOOKING_WARNING: 'Tickets are non-refundable 24 hours after booking and non transferable. Name changes are not allowed.',
				REVIEW_CAR_RENTAL: 'Review your car rental',
				STARTING_FROM: 'Starting from',
				TO: 'to',
				AUTO_TRANSMISSION: 'Automatic transmission',
				MANUAL_TRANSMISSION: 'Manual transmission',
				PICK_UP_ADDRESS: 'Pick up address',
				RETURN_ADDRESS: 'Return address',
				DAY: 'Day',
				CAR_RENTAL_SUMMARY: 'Car rental summary',
			    ONLY_WITH_DRIVER: 'Comes with driver',
			    TOTAL: 'Total',
			    CAR_RENTAL_ETHIOPIA: 'Your car rental in Ethiopia',
			    WHO_DRIVING: 'Who is driving?',
			    DRIVER_NAME: 'Traveler name must match government-issued ID exactly',
			    STREET_ADDRESS: 'Street Address',
			    
			    
			    PYRAMIDS_OF_GIZA: 'Pyramids of Giza - Egypt',
			    PYRAMIDS_OF_GIZA_DESC: 'For nearly 4000 years, the extraordinary shape, impeccable geometry and sheer bulk of the Giza Pyramids ...',
			    AGADIR: 'Agadir - Morocco',
                BWINDI: 'Bwindi Park - Uganda',
                AGADIR_DESC: 'Agadir feels unlike anywhere else in Morocco. A busy port and beach resort sprawling beneath its kasbah, the city was completely ..',
                BWINDI_DESC: 'Home to almost half of the world’s surviving mountain gorillas, the World Heritage–listed Bwindi Impenetrable National Park is one of ..',
			    TABLE_MOUNTAIN: 'Table Mountain - South Africa',
			    TABLE_MOUNTAIN_DESC: 'Around 600 million years old, and a canvas painted with the rich diversity of the Cape floral kingdom, Table Mountain is ...',
			    MASSAI_MARA: 'Massai Mara - Kenya',
			    MASSAI_MARA_DESC: 'The world-renowned Masai Mara National Reserve needs little in the way of introduction; its tawny, wildlife-stuffed savannahs ...',
			    NGORONGORO_CONS: 'Ngorongoro Conservation - Tanzania',
			    NGORONGORO_CONS_DESC: 'Lying within the boundaries of the 8292 sq km Ngorongoro Conservation Area are the Ngorongoro Crater, Oldupai Gorge ...',
			    COLOSSEUM_ELJEM: 'Colosseum at El-Jem - Tunisia',
			    COLOSSEUM_ELJEM_DESC: 'World Heritage-listed and quite possibly the single most impressive Roman monument in Africa, the colosseum at El-Jem was ...',
			    
			    ZULU: 'Zulu cultural ceremonies',
			    ZULU_PART1: 'If you visit the town of Eshowe in February, then you can witness a festival known as the first fruits ceremony, which was done by early Zulu kings. This particular event is held by a local sangoma (traditional healer) who goes by the name of Khekhekhe and involves poisonous snakes.',
			    ZULU_PART2: 'Khekhekhe (whose birth name was Zizwezonke Mthuthwa) lives in a homestead close to the Tugela River and invites fellow sangomas to attend this event, which takes place on 23 February every year.',
            
                SERVICE_LEVEL: 'Service level',
                CAMPING: 'Camping',
                BASIC: 'Basic',
                STANDARD: 'Standard',
                LUXURY: 'Luxury',
                TRANSPORTATION: 'Transportation',
                CAR: 'Automobile',
                PLANE: 'Plane',
                TRAIN: 'Train',
                FOOT: 'Foot',
                BUS: 'Bus',
                BICYCLE: 'Bicycle',
                MOTORCYCLE: 'Motorcycle',
                SHIP: 'Ship',
                SUBWAY: 'Subway',
                PHYSICAL_DEMAND: 'Physical Demand',
                MIN_AGE: 'Minimum Age',
                WITH_GUIDE: 'With tour guide?',
                ADD_PIC: 'Upload Picture',
                DETAILS: 'Details ...',
                SUCCESS_MESSAGE : 'Transaction Successfully Processed. We have sent you an email with details',
                OUT_OF: 'out of 5',
                PRICE: 'Price',
                INCLUDING_GUIDE: 'With Guide',
                EDIT: 'Edit',
                PACKAGE_EDIT: 'Edit Tour Package',
                RESET: 'Reset',
                UPDATE: 'Update',
                DELETE: 'Delete',
                USER_MANUAL: 'User Manual',
                PASSWORD_CHANGE: 'Password Change',
                CURRENT_PASSWORD: 'Current Password',
                NEW_PASSWORD: 'New Password',
                CONFIRM_PASSWORD: 'Confirm New Password',
                CONFIRM_PASSWORD_1: 'Confirm Password',
                VAN: 'Safari van',
                CRUISER: 'Safari land cruiser',
                EDIT_COMPANY: 'Edit Company info',
                UPDATE_CAR: 'Edit car detail',
                CREATE_OPERTOR_ACCOUNT: 'Enroll as Tour Operator Company',
                CREATE_ACCOUNT: 'Create Tour Operator Account',
                ACCOUNT_CREATE: 'Create Account',
                ACCOUNT_EXIST_WARNING: 'There is account associated with this email address',
                AGREEMENT_TERM: 'I agree to the ',
                PARTNERSHIP_AGREEMENT: 'Tour Operator Partnership agreement',
                LEGAL: 'Legal entity',
                IDENTIFICATION_CARD: 'Identification card',
                LICENSE: 'License',
                UPLOAD_FILES: "File Upload",
                FINISH: 'Finish',
                MESSAGE_SENT_1: 'We have received your files and we are reviewing them. This might take up-to 24 hours.',
                MESSAGE_SENT_2: 'Your accont will be activated once we finish the review. We will notify you by email if we need addational documents.',
                MESSAGE_SENT_3: 'please check back later',
                ID_CARD_DETAIL: 'Copy of the identification card (e.g., drivers license, tour guide license, passport ID page) of the person signing the partnership agreement on behalf of your company.',
                LICENSE_DETAIL: 'Copy of your license to operate tours in the country you operate; if applicable',
                LEGAL_DETAIL: 'Proof of legal entity (for example: incorporation document, business registration with local government) that shows that you have been in business at least for more than one year.',
                COMPANY_NAME: 'Company Name',

                ERROR_MESSAGE: 'Transaction failed',
                SUPPORT_EMAIL: 'Email: connection@touranb.com',  

            }
        },
        "am-ET": {
            translation: {
            	 CANCEL: 'ተወው',
                 OPTIONS: 'ምርጫዎች',
                 NAME: 'ስም',
                 CODE: 'መለያ ቁጥር',
                 REPORTS: 'ዘገባዎች',
                 TOURS: 'አስጎብኚዎች',
                 GROUPS: 'ቡድኖች',
                 SIGN_IN: 'መግቢያ',
                 LOGIN: 'መግቢያ',
                 USER_NAME: 'ስም',
                 PASSWORD: 'የይለፍ ቃል',
                 COPYRIGHT: 'መብቱ በህግ የተጠበቀ ነው',
                 FLIGHTS: 'በረራዎች',
                 HOTELS: 'ሆቴሎች',
                 BUNDLE_DEALS: 'ጥቅል',
                 CARS: 'መኪናዎች',
                 CRUISES: 'ጀልባዎች',
                 THINGS_TODO: 'አቅዶች',
                 VACATION_RENTALS: 'ኪራይ',
                 SEARCH: 'መፈለጊያ',
                 ROUND_TRIP: 'ደርሶ መልስ', 
                 ONE_WAY: 'መሄድ ብቻ', 
                 MULTIPLE_DESTINATIONS: 'ብዙ መዳረሻዎች', 
                 FLIGHT_HOTEL: 'በረራ + ሆቴል', 
                 FLIGHT_HOTEL_CAR: 'በረራ + ሆቴል + መኪና',
                 FLIGHT_CAR: 'በረራ + መኪና',
                 HOTEL_CAR: 'ሆቴል + መኪና',
            }
        },
        "fr-FR": {
            translation: {
            	CANCEL: 'Annuler',
                OPTIONS: 'les options',
                NAME: 'le nom',
                TOURS: 'les voyages organisés',
                GROUPS: 'les groups',
                CUSTOM_TOUR: 'les voyages customisés',
                NEW_GROUP: 'un nouveau groupe',
                SIGN_IN: 's’identifiez',
                LOGIN: 'la connexion',
                USER_NAME: 'le nom d’utilisateur',
                PASSWORD: 'le mot de passe',
                COPYRIGHT: 'le droit d’auteur',
                FLIGHTS: 'Flights',
                HOTELS: 'Hotels',
                BUNDLE_DEALS: 'Bundle Deals',
                CARS: 'les voitures',
                CRUISES: 'Cruises',
                THINGS_TODO: 'Things to Do',
                VACATION_RENTALS: 'Vacation Rentals',
                SEARCH: 'recherche',
                ROUND_TRIP: 'Round Trip', 
                ONE_WAY: 'One Way', 
                MULTIPLE_DESTINATIONS: 'Multiple Destinations', 
                FLIGHT_HOTEL: 'Flight + Hotel', 
                FLIGHT_HOTEL_CAR: 'Flight + Hotel + Car', 
                FLIGHT_CAR: 'Flight + Car', 
                HOTEL_CAR: 'Hotel + Car',
                REGISTER: 'inscrivez',
                HELP: 'aidez',
                MORE: 'plus',
                PAGE_NOT_FOUND: "page non trouvée",
                WE_COULDNT_FIND_THE_PAGE: "désolé, nous ne pouvons pas trouver la page que vous cherchez",
                LET_US_KNOW_IF_U_FIND_IT: "Please let us know if find you it",
                FESTIVALS_AND_EVENTS: "Les festivals et événements prochains",
                EMAIL: 'Email',
                TOUR_TYPE: 'le type du voyage organisé',
                TRAVELLERS: 'les voyageurs',
                TRIP_DATE: 'la date du voyage',
                ALL_INCLUSIVE: 'tous compris',
                TRIP_DURATION: 'la durée du voyage',
                DESCRIPTION: 'la description',
                GROUP_NAME: 'le nom du groupe',
                CREATE_GROUP: 'créez un groupe',
                SUBMIT: 'soumettez',
                DAYS: 'les jours',
                JAN: 'janv',
                SEP: 'sept',
                SELECT_LANGUGAGE: 'sélectionnez la langue',
                SELECT_VISITING_COUNTRY: 'Select Visiting Country',
                GENNA: 'Genna (Noel éthiopienne)',
                GENNA_PAR1: 'La Noel, qui est fêté le 7 janvier, est nommé Ledet où Genna, qui vient du mot Gennana, qui signifie « imminent » et qui exprime l’arrivée du Seigneur et la libération de l’humanité du péché.',
                GENNA_PAR2: 'La fêté de Noel éthiopienne est marquée par de plusieurs activités y compris les courses de chevaux et les danses folk traditionnelles. À Lalibela, Genna est fêté à façons très belles à cause de la date de naissance du roi Lalibela qui était un jour similaire. Aux régions un jeu populaire qui ressemble au hockey sur gazon européen mais est typiquement éthiopienne, est conduit contre deux équipes des jeunes. Le jeu reçoit le nom du festival et c’est appelé « Yegena Chewata. »',
                TIMKET: 'l’Epiphanie éthiopienne',
                TIMKET_PAR1: 'Timket est un des festivals plus remarquable des chrétiennes orthodoxes en Ethiopie. Il célèbre le baptême de Christ et se déroule le 19 janvier (20 janvier pendant les années bissextiles). C’est un événement de trois jours, qui commence au Veille de Timkat avec des processions dramatique et coloré.',
                TIMKET_PAR2: 'Le Veille de Timkat est appelé Ketera et c’est quand les Tabots de chaque église sont transportés à une rivière ou une mare où le fête du lendemain se déroulera.',
                TIMKET_PAR3: 'Le matin suivant, le grand jour lui-même, le Baptême de Christ dans la fleuve Jordan par saint Jean le baptiste est commémoré. Le troisième jour est consacré à la Fête de Saint Michael, l’archange, un des saints bien-connu en Ethiopie.',
                FASIKA: 'Fasika (Pacques orthodoxe)',
                FASIKA_PAR1: 'Pacques est un des fêtes le plus célèbre vivement à l’église orthodoxe éthiopienne et c’est un festival plus importante que le Noel, et la mort a un sens plus grand que la naissance au christianisme orthodoxe. Similaire aux autres festivals, Pacques est célébré vivement a Axum et Lalibela.',
                FASIKA_PAR2: 'Chaque veille de Pacques, des gens vont a l’église et célèbrent avec des bougies qui sont allumé et qui forme une pièce importante de la messe de Pacques qui commence a 6h de l’après-midi et fini environ a 2h du matin. Après, tout le monde retourne a la maison pour le rupture du jeûne.',
                ENKUTATASH: 'Enkutatash (Nouvelle année éthiopienne)',
                ENKUTATASH_PAR1: 'L’Ethiopie utilise encore le calendrier Julian, où l’année est divisée en 12 mois de 30 jours et un treizième mois de 5 jours avec 6 jours a l’année bissextile. La nouvelle année est célébrée le 11 septembre et le jour lui-même est appelé Enkutatash, qui est défini comme « don des bijoux. » C’est un événement très spectaculaire.',
                ENKUTATASH_PAR2: 'Ce festival célèbre a la fois la nouvelle année et la fête de Saint Jean-Baptiste. Cet événement printanier spécial',
                MESKEL: 'Meskel (Finding of the True Cross)',
                MESKEL_PAR1: 'The actually word Meskel means "cross" and the feast commemorates the discovery of the cross upon which Jesus was crucified by the Empress Helena, the mother of Constantine the Great.',
                MESKEL_PAR2: 'This day is celebrated with plenty of food and drink and believers go to the spot of the Demera and, using ashes from the fire, mark their foreheads with the sign of the cross. The most ideal place to see the Meskel Festival is in the capital Addis Ababa at the famous Meskel Square but all along the historic route (Bahir Dar, Gonder, Axum, and Lalibela) and in other major towns, Meskel is colorfully celebrated.',
                MESKEL_PAR3: 'Meskal has been celebrated in the country for over 1600 years and is a very popular festival in Ethiopia and gives everyone the opportunity to sing, dance and dress in colourful robes.',
                ADDIS_ABABA: 'Addis Ababa',
                ADDIS_ABABA_DESC: 'Since its establishment in 1886, Addis Ababa (Amharic: ??????) has always seemed like a magical portal...',
                LALIBELA: 'Lalibela',
                LALIBELA_DESC: 'Lalibela is history and mystery frozen in stone, its soul alive with the rites and awe of Christianity...',
                GONDAR: 'Gondar',
                GONDAR_DESC: 'It’s not what Gonder is, but what Gonder was that’s so enthralling....',
                AXUM: 'Axum',
                AXUM_DESC: 'Does the very same Ark of the Covenant that holds Moses’ 10 Commandments reside in a small Aksum chapel?...',
                DIREDAWA: 'Diredawa',
                DIREDAWA_DESC: 'The fourth-most populous city in Ethiopia, Dire Dawa usually elicits strong reactions...',
                HARAR: 'Harar',
                HARAR_DESC: 'The town of Harar dates from before the thirteenth century. Its strategic location between the coastal lowlands and central highlands led to...',
                SEMIEN_MOUNTAINS: 'Semien Mountains',
                SEMIEN_MOUNTAINS_DESC: 'No matter how you look at them, the Simien Mountains are awesome. This massive plateau, riven with gullies and pinnacles...',
                DALLOL: 'Dallol (Volcano)',
                DALLOL_DESC: 'The term Dallol was coined by the Afar people and means dissolution or disintegration describing a landscape made up of green acid ponds...',
                THE_LOWER_OMO_VALLEY: 'The Lower Omo Valley',
                THE_LOWER_OMO_VALLEY_DESC: 'The villages of the Lower Omo Valley are home to some of Africa’s most fascinating ethnic groups...',
                ROCK_HEWN_CHURCHES_OF_TIGRAY: 'Rock-hewn Churches of Tigray',
                ROCK_HEWN_CHURCHES_OF_TIGRAY_DESC: 'The landscapes of northern Tigray are almost fairytale-like. The luminous light bathes scattered sharp peaks that rise high into the sky...',
                BALE_MOUNTAINS_NATIONAL_PARK: 'Bale Mountains National Park',
                BALE_MOUNTAINS_NATIONAL_PARK_DESC: 'More than any other park in Ethiopia, this soon-to-be World Heritage site is known for its wildlife, but it’s a very beautiful place, too',
                DANAKIL_DEPRESSION: 'Danakil Depression',
                DANAKIL_DEPRESSION_DESC: 'Bubbling volcanoes light up the night sky, sulphurous mounds of yellow contort into otherworldly shapes...',
                BACK: 'Back',
                INFORMATION: 'les renseignements',
                WARNING: 'avertissement',
                FAILED: 'raté',
                SUCCESS: 'succès',
                FIRST_NAME: 'le prénom',
                LAST_NAME: 'le nom de famille',
                CONFIRM_PASSWORD: 'confirmez le mot de passe',
                SEX: 'le sexe',
                BIRTHDAY: 'l’anniversaire',
                PHONE_NUMBER: 'le numéro de téléphone',
                LOCATION: 'l’endroit',
                CLOSE: 'fermez',
                SELECT: 'sélectionnez',
                DATE: 'la date',
                TRIP_STARTS_AT: 'le voyage commence à',
                PEOPLE_IN_GROUP: 'les personnes dans ce groupe.',
                FOUND_NOTHING: 'on ne trouve rien',
                MATCHES: 'les paires',
                ADD_ME: 'ajoutez-moi',
                CONNECTION_ERROR: 'désolé, on ne peut pas connecter au serveur. S’il vous plait, essayez encore.',
                OTHER: 'l’autre',
                COUNTRY: 'le pays',
                INCLUDING_ACCOMMODATION_AND_MEAL: 'y compris le logement et un repas',
                MALE: 'homme',
                FEMALE: 'femme',
                CONFIRM_PASSWORD_WARNING: 'les deux mots de passe que vous avez entrée n’est pas les même choses',
                PICKING_UP: 'aller chercher',
                DROPPING_OFF: 'déposer',
                PICKUP_DATE: 'la date d’aller chercher',
                DROPOFF_DATE: 'la date de déposer ',
                TRAVEL_AGENT_NAME: 'le voyagiste',
                FAX: 'le fax',
                AIRPORT_PICKUP: 'le transfert de l’aéroport',
                CITY: 'la ville',
                SUB_CITY: 'Sub-City',
                COUNTY: 'le pays',
                KEBELE: 'Kebele',
                BUILDING_NAME: 'le bâtiment',
                PACKAGE_REGISTRATION: 'l’inscription du paquet du voyage organisé',
                TOUR_MAX_SIZE: 'la taille maximum',
                TOUR_MIN_SIZE: 'la taille minimum',
                TOUR_START_DATE: 'la date de début',
                TOUR_END_DATE: 'la date de fin',
                TOUR_DURATION: 'la durée',
                TOUR_START_PLACE: 'le point de départ',
                TOUR_START_TIME: 'l’heure de début',
                TOUR_ROUTE: 'la route du voyage organisé',
                ALL_YEAR_ROUND_TRIP: 'le voyage toute l’année',
                FIXED_DATE_TRIP: 'la date fixée du voyage',
                TOUR_PACKAGES: 'les paquets du voyage organisé',
                CAR_REGISTRY: 'l’enregistrement de la voiture',
                SEASON: 'les saisons',
                BASIC_ONLY: 'seulement basique',
                MAKE: 'Make',
                MODEL: 'Model',
                PASSENGER_SIZE: 'Passenger Size',
                DOOR_COUNT: 'Doors',
                RETURN_ADDRESS_THE_SAME: 'Is Return Address the Same?',
                CARS_COUNT: 'No. of Cars',
                HOUSE_NUMBER: 'House Number',
                CAR_REGISTRATION: 'Car Registration',
                WITH_DRIVER: 'Only With Driver',
                DAILY_PRICE: 'Daily Price',
                YES: 'Yes',
                TRIP_START_DATE: 'Trip Start Date',
                TRIP_END_DATE: 'Trip End Date',
                ETHIOPIA: 'l’Éthiopie',
                KENYA: 'le Kenya',
                TANZANIA: 'la Tanzanie',
                UGANDA: 'l’Ouganda',
                CONGO: 'Congo', 
                MOROCCO: 'Morocco', 
                SOUTH_AFRICA: 'South Africa',
                MALI: 'Mali', 
                ZAMBIA: 'Zambia', 
                ZIMBABWE: 'Zimbabwe', 
                EGYPT: 'Egypt', 
                TUNISIA: 'Tunisia', 
                GHANA: 'Ghana',
                SAME_AS_PICKUP: 'Same as Pick-up',
                TOURS_DESCRIPTION_1: 'Please select a Tour Type and search to see available tours for that tour category. The system will pull tour package details from more than 50 Tour Operators that work in the country.',
                TOURS_DESCRIPTION_2: 'Travelers often go in groups to save money and have a pleasant experience. We recommend you to check the groups tab to see if there is already a group of people who will take that trip on the similar time span.',
                AUTOMATIC_TRANSMISSION: 'Automatic Transmission',
                MY_CARS: 'My Cars',
                MY_TOURS: 'My Tours',
                CAR_ID: 'Car Id',
                TOUR_ID: 'Tour Id',
            }
        },
        "de-DE": {
            translation: {
                CANCEL: 'Stornieren',
                OPTIONS: 'Optionen',
                NAME: 'Name',
                CODE: 'Code',
                REPORTS: 'Berichte',
                TOURS: 'Tours',
                GROUPS: 'Gruppen',
                CUSTOM_TOUR: 'Individuelle Reise',
                NEW_GROUP: 'Neue Gruppe',
                SIGN_IN: 'Anmelden',
                LOGIN: 'Anmelden',
                USER_NAME: 'E-Mail-Adresse',
                PASSWORD: 'Passwort',
                COPYRIGHT: 'Copyright',
                REGISTER: 'Neu registrieren',
                HELP: 'Hilfe',
                MORE: 'Mehr',
                PAGE_NOT_FOUND: "Page Not Found",
                WE_COULDNT_FIND_THE_PAGE: "Sorry, we couldn't find the page you were looking for.",
                LET_US_KNOW_IF_U_FIND_IT: "Please let us know if find you it",
                FESTIVALS_AND_EVENTS: "Upcoming Festivals and Events",
                EMAIL: 'Email',
            }
        },
        "it-IT": {
            translation: {
                OPTIONS: 'Opzioni',
                NAME: 'Nome',
                CODE: 'Codice',
                REPORTS: 'Rapporti',
                TOURS: 'Tours',
                GROUPS: 'Gruppi',
                CUSTOM_TOUR: 'Tour personalizzati',
                NEW_GROUP: 'Nuovo gruppo',
                SIGN_IN: 'Effettua l’accesso',
                LOGIN: 'Effettua l’accesso',
                USER_NAME: 'Indirizzo e-mail',
                PASSWORD: 'Password',
                COPYRIGHT: 'Diritto d’autore',
                REGISTER: 'Registro',
                HELP: 'Aiuto',
                MORE: 'Di Più',
                PAGE_NOT_FOUND: "Page Not Found",
                WE_COULDNT_FIND_THE_PAGE: "Sorry, we couldn't find the page you were looking for.",
                LET_US_KNOW_IF_U_FIND_IT: "Please let us know if find you it",
                FESTIVALS_AND_EVENTS: "Upcoming Festivals and Events",
                EMAIL: 'E-mail',
            }
        },
        "es-ES": {
            translation: {
                CANCEL: 'Cancelar',
                OPTIONS: 'Opciones',
                NAME: 'Nombre',
                TOURS: 'Recorridos',
                GROUPS: 'Grupos',
                CUSTOM_TOUR: 'Recorrido a medida',
                NEW_GROUP: 'Nuevo grupo',
                SIGN_IN: 'Acceder',
                LOGIN: 'Acceso',
                USER_NAME: 'Nombre de usuario',
                PASSWORD: 'Contraseña',
                COPYRIGHT: 'Derechos del autor',
                FLIGHTS: 'Flights',
                HOTELS: 'Hotels',
                BUNDLE_DEALS: 'Bundle Deals',
                CARS: 'Coches',
                CRUISES: 'Cruises',
                THINGS_TODO: 'Things to Do',
                VACATION_RENTALS: 'Vacation Rentals',
                SEARCH: 'Buscar',
                ROUND_TRIP: 'Round Trip', 
                ONE_WAY: 'One Way', 
                MULTIPLE_DESTINATIONS: 'Multiple Destinations', 
                FLIGHT_HOTEL: 'Flight + Hotel', 
                FLIGHT_HOTEL_CAR: 'Flight + Hotel + Car', 
                FLIGHT_CAR: 'Flight + Car', 
                HOTEL_CAR: 'Hotel + Car',
                REGISTER: 'Registrar',
                HELP: 'Ayuda',
                MORE: 'Más',
                PAGE_NOT_FOUND: "Página no encontrada",
                WE_COULDNT_FIND_THE_PAGE: "Lo siento, no podemos buscar la página que estás buscando",
                LET_US_KNOW_IF_U_FIND_IT: "Please let us know if find you it",
                FESTIVALS_AND_EVENTS: "Próximos festivales y eventos",
                EMAIL: 'Correo electrónico',
                TOUR_TYPE: 'Tipo de recorrido',
                TRAVELLERS: 'Viajeros',
                TRIP_DATE: 'Fecha del viaje',
                ALL_INCLUSIVE: 'Con todo incluido',
                TRIP_DURATION: 'Duración del viaje',
                DESCRIPTION: 'Descripción',
                GROUP_NAME: 'Nombre del grupo',
                CREATE_GROUP: 'Crea un grupo',
                SUBMIT: 'Enviar',
                DAYS: 'Días',
                JAN: 'Enero',
                SEP: 'Sept.',
                SELECT_LANGUGAGE: 'Elige el lenguaje',
                SELECT_VISITING_COUNTRY: 'Elige el país invitado',
                GENNA: 'Genna (Navidad etiope)',
                GENNA_PAR1: 'Christmas, which is celebrated on the 7th January, is called Ledet or Genna which comes from the word Gennana, meaning “imminent” and which expresses the coming of the Lord and the freeing of mankind from sin.',
                GENNA_PAR2: 'The celebration of Ethiopian Christmas is marked by various activities such as horse racing   and authentic folk dancing. At Lalibela, Genna is celebrated in very attractive ways due to the birth date of King Lalibela being on a similar day. In the rural areas a popular game which looks like European Hockey but is typically Ethiopian is conducted between two youth teams. The game is named after the festival and is called "Yegena Chewata".',
                TIMKET: 'Timket (Epifanía etiope)',
                TIMKET_PAR1: 'Timket is one of the most remarkable festivals of Orthodox Christians in Ethiopia. It celebrates the Baptism of Christ and takes place each January 19th (January 20th during leap years). It is a three-day event, beginning on the Eve of Timkat with dramatic and colorful processions.',
                TIMKET_PAR2: 'The eve of Timket is called Ketera and this is when the Tabots of each church are carried out in procession to a river or pool of water where the next day\'s celebration will take place.',
                TIMKET_PAR3: 'The following morning, the great day itself, Christ\'s Baptism in the Jordan River by John the Baptist is commemorated. The third day is committed to the Feast of St. Michael, the archangel, one of the Ethiopia\'s well known saints.',
                FASIKA: 'Fasika (Pascua ortodoxa)',
                FASIKA_PAR1: 'Pacques est une des fêtes les plus vivement célébrées de l’église orthodoxe éthiopienne. C’est plus important que noël parce qu’un mort est plus signifiant d’une naissance dans la tradition chrétien orthodoxe. Comme des autres fêtes, Pacques est célébrée très vivement à Axum et Lalibela.',
                FASIKA_PAR2: 'À nuit de Pâques les gens vont à l’église et célèbrent avec des cierges, une partie très important de la messe du Pacques, qui commence à 18h et fini à 02h. Après la messe, tout le monde retour à la maison pour finir leur jeûne. ',
                ENKUTATASH: 'Enkutatash (Año Nuevo etiope)',
                ENKUTATASH_PAR1: 'Ethiopia still retains the Julian calendar in which the year is divided into 12 months of 30 days each and a 13th month of 5 days with 6 days in a leap year. The New Year is celebrated on 11th September and the day itself is called Enkutatash, which means “gift of jewels.”  It is a most spectacular event.',
                ENKUTATASH_PAR2: 'This festival celebrates both the New Year and the Feast of John the Baptist. This special spring event has been celebrated since early times and as the rains come to an end. Children dressed in new clothes dance through the villages distributing garlands and tiny paintings. In the evening each house lights a bonfire and there is much singing and dancing.',
                MESKEL: 'Meskel (Descubrimiento de la cruz verdadera)',
                MESKEL_PAR1: 'The actually word Meskel means "cross" and the feast commemorates the discovery of the cross upon which Jesus was crucified by the Empress Helena, the mother of Constantine the Great.',
                MESKEL_PAR2: 'This day is celebrated with plenty of food and drink and believers go to the spot of the Demera and, using ashes from the fire, mark their foreheads with the sign of the cross. The most ideal place to see the Meskel Festival is in the capital Addis Ababa at the famous Meskel Square but all along the historic route (Bahir Dar, Gonder, Axum, and Lalibela) and in other major towns, Meskel is colorfully celebrated.',
                MESKEL_PAR3: 'Meskal has been celebrated in the country for over 1600 years and is a very popular festival in Ethiopia and gives everyone the opportunity to sing, dance and dress in colourful robes.',
                ADDIS_ABABA: 'Addis Ababa',
                ADDIS_ABABA_DESC: 'Since its establishment in 1886, Addis Ababa (Amharic: ??????) has always seemed like a magical portal...',
                LALIBELA: 'Lalibela',
                LALIBELA_DESC: 'Lalibela is history and mystery frozen in stone, its soul alive with the rites and awe of Christianity...',
                GONDAR: 'Gondar',
                GONDAR_DESC: 'It’s not what Gonder is, but what Gonder was that’s so enthralling....',
                AXUM: 'Axum',
                AXUM_DESC: 'Does the very same Ark of the Covenant that holds Moses’ 10 Commandments reside in a small Aksum chapel?...',
                DIREDAWA: 'Diredawa',
                DIREDAWA_DESC: 'The fourth-most populous city in Ethiopia, Dire Dawa usually elicits strong reactions...',
                HARAR: 'Harar',
                HARAR_DESC: 'The town of Harar dates from before the thirteenth century. Its strategic location between the coastal lowlands and central highlands led to...',
                SEMIEN_MOUNTAINS: 'Semien Mountains',
                SEMIEN_MOUNTAINS_DESC: 'No matter how you look at them, the Simien Mountains are awesome. This massive plateau, riven with gullies and pinnacles...',
                DALLOL: 'Dallol (Volcano)',
                DALLOL_DESC: 'The term Dallol was coined by the Afar people and means dissolution or disintegration describing a landscape made up of green acid ponds...',
                THE_LOWER_OMO_VALLEY: 'The Lower Omo Valley',
                THE_LOWER_OMO_VALLEY_DESC: 'The villages of the Lower Omo Valley are home to some of Africa’s most fascinating ethnic groups...',
                ROCK_HEWN_CHURCHES_OF_TIGRAY: 'Rock-hewn Churches of Tigray',
                ROCK_HEWN_CHURCHES_OF_TIGRAY_DESC: 'The landscapes of northern Tigray are almost fairytale-like. The luminous light bathes scattered sharp peaks that rise high into the sky...',
                BALE_MOUNTAINS_NATIONAL_PARK: 'Bale Mountains National Park',
                BALE_MOUNTAINS_NATIONAL_PARK_DESC: 'More than any other park in Ethiopia, this soon-to-be World Heritage site is known for its wildlife, but it’s a very beautiful place, too',
                DANAKIL_DEPRESSION: 'Danakil Depression',
                DANAKIL_DEPRESSION_DESC: 'Bubbling volcanoes light up the night sky, sulphurous mounds of yellow contort into otherworldly shapes...',
                BACK: 'Regresar',
                INFORMATION: 'Información',
                WARNING: 'Advertencia',
                FAILED: 'Fallado',
                SUCCESS: 'Logrado',
                FIRST_NAME: 'Nombre de pila',
                LAST_NAME: 'Apellido',
                CONFIRM_PASSWORD: 'Confirma contraseña',
                SEX: 'Sexo',
                BIRTHDAY: 'Cumpleaños',
                PHONE_NUMBER: 'PNúmero de teléfono',
                LOCATION: 'Lugar',
                CLOSE: 'Cerrar',
                SELECT: 'Elegir',
                DATE: 'Fecha',
                TRIP_STARTS_AT: 'Viaje comienza a ',
                PEOPLE_IN_GROUP: 'Personas en este grupo',
                FOUND_NOTHING: 'Descubrió nada',
                MATCHES: 'Matches',
                ADD_ME: 'Add Me',
                CONNECTION_ERROR: 'Lo siento, no podemos conectar con el servidor. Por favor hace otra vez',
                OTHER: 'Otro',
                COUNTRY: 'País',
                INCLUDING_ACCOMMODATION_AND_MEAL: 'Incluyendo alojamiento y comida',
                MALE: 'Hombres',
                FEMALE: 'Mujéres',
                CONFIRM_PASSWORD_WARNING: 'Las dos contraseñas que te entraron no son iguales.',
                PICKING_UP: 'Recogiendo',
                DROPPING_OFF: 'Dejando',
                PICKUP_DATE: 'Fecha de recoger',
                DROPOFF_DATE: 'Fecha de dejar',
                TRAVEL_AGENT_NAME: 'Agente de viajes',
                FAX: 'Fax',
                AIRPORT_PICKUP: 'Recogida en el aeropuerto',
                CITY: 'Ciudad',
                SUB_CITY: 'Sub-ciudad',
                COUNTY: 'Condado',
                KEBELE: 'Kebele',
                BUILDING_NAME: 'Edificio',
                PACKAGE_REGISTRATION: 'Registración para viajes organizados',
                TOUR_MAX_SIZE: 'Tamaño máximo',
                TOUR_MIN_SIZE: 'Tamaño mínimo',
                TOUR_START_DATE: 'Fecha de empezar',
                TOUR_END_DATE: 'Fecha de terminar',
                TOUR_DURATION: 'Duración',
                TOUR_START_PLACE: 'Lugar de empezar',
                TOUR_START_TIME: 'Hora de empezar',
                TOUR_ROUTE: 'Ruta del recorrido',
                ALL_YEAR_ROUND_TRIP: 'Viaje de todo el año',
                FIXED_DATE_TRIP: 'Viaje de fecha fija',
                TOUR_PACKAGES: 'Viajes organizados',
                CAR_REGISTRY: 'Registro de coches',
                SEASON: 'Estaciones',
                BASIC_ONLY: 'Solamente básico',
                MAKE: 'Make',
                MODEL: 'Modelo',
                PASSENGER_SIZE: 'Passenger Size',
                DOOR_COUNT: 'Puertas',
                RETURN_ADDRESS_THE_SAME: 'Is Return Address the Same?',
                CARS_COUNT: 'Número de coches',
                HOUSE_NUMBER: 'Número de casa',
                CAR_REGISTRATION: 'Registración de coches',
                WITH_DRIVER: '¿Con conductor?',
                DAILY_PRICE: 'Precio diario',
                YES: 'Sí',
                TRIP_START_DATE: 'Fecha de empezar del viaje',
                TRIP_END_DATE: 'Fecha de terminar del viaje',
                ETHIOPIA: 'Etiopía',
                KENYA: 'Kenia',
                TANZANIA: 'Tanzania',
                UGANDA: 'Uganda',
                CONGO: 'Congo', 
                MOROCCO: 'Morocco', 
                SOUTH_AFRICA: 'South Africa',
                MALI: 'Mali', 
                ZAMBIA: 'Zambia', 
                ZIMBABWE: 'Zimbabwe', 
                EGYPT: 'Egypt', 
                TUNISIA: 'Tunisia', 
                GHANA: 'Ghana',
                SAME_AS_PICKUP: 'Same as Pick-up',
                TOURS_DESCRIPTION_1: 'Please select a Tour Type and search to see available tours for that tour category. The system will pull tour package details from more than 50 Tour Operators that work in the country.',
                TOURS_DESCRIPTION_2: 'Travelers often go in groups to save money and have a pleasant experience. We recommend you to check the groups tab to see if there is already a group of people who will take that trip on the similar time span.',
                AUTOMATIC_TRANSMISSION: 'Automatic Transmission?',
                MY_CARS: 'My Cars',
                MY_TOURS: 'My Tours',
                CAR_ID: 'Car Id',
               
                
            }
        },
    }
},
function(err, t) {
    
});